spring:
  datasource:
    url: jdbc:h2:tcp://localhost/C:\my2023programs\inflearn\jpa\jpa_use_1/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  logging.level:
    org.hibernate.SQL: debug
